New branch
YahyoMahmudov/Unit-Tests-with-Typescript pull request #2
Opened 2024-02-09 10:43 UTC by YahyoMahmudov

2024-02-11 10:32 UTC, jkalandarov commented on task1/Calculator.test.ts
> +var calculator = new Calculator();
I recommend using `let` or `const` over `var`.

2024-02-11 11:00 UTC, jkalandarov requested changes

2024-02-11 11:00 UTC, jkalandarov commented on task1/Calculator.ts
> +            return NaN;
In case of invalid type, it's better to throw an error.

2024-02-11 11:00 UTC, jkalandarov commented on task2/DivisibleBy.test.ts
> +})
Are you checking if a given number is divisible by 3? if so, 3 is divisible by 3.

2024-02-11 11:00 UTC, jkalandarov commented on task2/DivisibleBy.test.ts
> +})
Are you checking if a given number is divisible by 5? if so, 5 is divisible by 5.

2024-02-11 11:00 UTC, jkalandarov commented on task2/DivisibleBy.test.ts
> +
The test names are confusing.

2024-02-11 11:00 UTC, jkalandarov commented on task3/ArrayParam.test.ts
> +})
John's age is below 18. According to the test name, the result should be `true`.

2024-02-11 11:00 UTC, jkalandarov commented on task3/ArrayParam.test.ts
> +})
Jack's age is not above or equal to 18. The result should be `true`.

2024-02-11 11:00 UTC, jkalandarov commented on task3/ArrayParam.test.ts
> +})
None of the object's age is not above or equal to 18, the result should be `true` for all cases.

2024-02-11 11:00 UTC, jkalandarov commented on task3/ArrayParam.test.ts
> +})
What if one of the object's age is below 18? How do you handle such cases?

2024-02-11 11:00 UTC, jkalandarov commented on task3/ArrayParam.ts
> +export function arrayParam(arr: { name: string, age: number }[]): boolean {
function's name should be a verb and tell what this function does. 
Check these [naming conventions](https://www.syncfusion.com/blogs/post/top-javascript-naming-convention.aspx) in programming.

2024-02-11 11:00 UTC, jkalandarov commented on task4/DateFormat.ts
> +
Don't leave extra spaces if there's no need for them.

2024-02-11 11:00 UTC, jkalandarov commented on task4/DateFormat.ts
> +
It's recommended not to leave unnecessary comments.

2024-02-11 11:00 UTC, jkalandarov commented on task4/DateFormat.ts
> +
Your code should be self documenting and should not leave a need for comments.

2024-02-12 02:40 UTC, YahyoMahmudov commented on task2/DivisibleBy.test.ts
> +})
I am checking that the number is divisible by both 3 and 5, not just one of them.

2024-02-12 02:42 UTC, YahyoMahmudov commented on task3/ArrayParam.test.ts
> +})
According to the task description, all people's age should be 18 or above. Am I right?

2024-02-12 07:18 UTC, YahyoMahmudov commented on task2/DivisibleBy.test.ts
> +})
I am checking that the number is divisible by both 3 and 5, not just one of them.

2024-02-12 07:19 UTC, YahyoMahmudov commented on task3/ArrayParam.test.ts
> +})
If one age is below 18, it should be false.

2024-02-12 07:34 UTC, YahyoMahmudov commented on task3/ArrayParam.test.ts
> +})
Does the "above 18" mean higher than 18 or lower than 18? I think it is higher than 18. So, this test should be false.

2024-02-12 07:35 UTC, YahyoMahmudov commented on task3/ArrayParam.test.ts
> +})
According to the description, if one of them is above 18, it should be false.

2024-02-12 08:34 UTC, jkalandarov approved these changes
Good job!

2024-02-12 08:54 UTC, merged